Maanaim.Web/Models/ErrorViewModel.cs
using System;

namespace Maanaim.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Maanaim.Web/Models/MongoDBStorageConfig.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Maanaim.Web.Models
{
    public class MongoDBStorageConfig
    {
        public string ConnectionString { get; set; }
    }
}

Maanaim.Web/Controllers/AdmController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Maanaim.Models;
using Microsoft.Extensions.Options;
using Maanaim.Web.Models;
using Maanaim.Model;
using Maanaim.Web.ViewModel;
using Maanaim.Web.ExtensionMethods;

namespace Maanaim.Web.Controllers
{
    public class AdmController : Controller
    {
        private readonly IOptions<MongoDBStorageConfig> config;

        public AdmController(IOptions<MongoDBStorageConfig> config)
        {
            this.config = config;
        }

        public IActionResult Index()
        {
            var colCalendar = new Data.DataCalendar(config.Value.ConnectionString).List().ToList<Calendar>();
            return View(colCalendar);
        }

        public IActionResult Gerenciar()
        {
            var colCalendar = new Data.DataCalendar(config.Value.ConnectionString).List().ToList<Calendar>();
            var colCalendarForm = from calendar in colCalendar
                                  select calendar.ToCalendarForm();
            return View(colCalendarForm.ToList());
        }

        [HttpGet]
        public IActionResult Visualizar(string Id)
        {
            CalendarForm calendarForm = (new Data.DataCalendar(config.Value.ConnectionString)).Find(Id).ToCalendarForm();

            return View("Visualizar", calendarForm);
        }

        [HttpGet]
        public IActionResult IncluirAlterar(string Id)
        {
            CalendarForm calendarForm;
            if (!string.IsNullOrEmpty(Id))
                calendarForm = (new Data.DataCalendar(config.Value.ConnectionString)).Find(Id).ToCalendarForm();
            else
            {
                calendarForm = new CalendarForm();
                calendarForm.StartDate = DateTime.Now.ToString("dd/MM/yyyy") + " 18:00:00";
                calendarForm.EndDate = calendarForm.StartDate;
            }

            return View("IncluirAlterar", calendarForm);
        }

        [HttpPost]
        public IActionResult IncluirAlterar(CalendarForm calendarForm)
        {


            try
            {

                var calendar = calendarForm.ToCalendar();

                if (string.IsNullOrEmpty(calendarForm.Id))
                {
                    (new Data.DataCalendar(config.Value.ConnectionString)).Insert(calendar);
                    calendarForm = new CalendarForm();
                    calendarForm.StartDate = DateTime.Now.ToString("dd/MM/yyyy") + " 18:00:00";
                    calendarForm.EndDate = calendarForm.StartDate;
                    ViewData["Message"] = "Programação incluída com sucesso!";
                }
                else
                {
                    (new Data.DataCalendar(config.Value.ConnectionString)).Update(calendar);
                    ViewData["Message"] = "Programação alterada com sucesso!";
                }



                ViewData["MessageClass"] = "alert-success";

            }
            catch (Exception ex)
            {
                ViewData["Message"] = "Ocorreu um erro. (" + ex.Message + ")";
                ViewData["MessageClass"] = "alert-danger";
            }



            return View(calendarForm);
        }


        [HttpPost]
        public IActionResult Excluir(CalendarForm calendarForm)
        {
            //ViewBag.Message = "Ocorreu um erro. (" + ex.Message + ")";
            //ViewBag.MessageClass = "alert-danger";
            try
            {

                var calendar = calendarForm.ToCalendar();

                if (string.IsNullOrEmpty(calendarForm.Id))
                {
                    throw new Exception("não foi possível excluir");
                }
                else
                {
                    (new Data.DataCalendar(config.Value.ConnectionString)).Delete(calendar);
                }

            }
            catch (Exception ex)
            {
                ViewBag.Message = "Ocorreu um erro. (" + ex.Message + ")";
                ViewBag.MessageClass = "alert-danger";
            }

            var colCalendar = new Data.DataCalendar(config.Value.ConnectionString).List().ToList<Calendar>();
            var colCalendarForm = from calendar in colCalendar
                                  select calendar.ToCalendarForm();
            return View("Gerenciar", colCalendarForm.ToList());
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Maanaim.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Maanaim.Models;
using Microsoft.Extensions.Options;
using Maanaim.Web.Models;
using Maanaim.Model;
using Maanaim.Web.ViewModel;
using Maanaim.Web.ExtensionMethods;


namespace Maanaim.Controllers
{
    public class HomeController : Controller
    {
        private readonly IOptions<MongoDBStorageConfig> config;

        public HomeController(IOptions<MongoDBStorageConfig> config)
        {
            this.config = config;
        }

        public IActionResult Index()
        {
            var colCalendar = new Data.DataCalendar(config.Value.ConnectionString).List().ToList<Calendar>();
            return View("~/Views/Adm/Index.cshtml",colCalendar);
        }

        [HttpGet]
        public IActionResult Visualizar(string Id)
        {
            CalendarForm calendarForm = (new Data.DataCalendar(config.Value.ConnectionString)).Find(Id).ToCalendarForm();

            return View("~/Views/Adm/Visualizar.cshtml", calendarForm);
        }
    }
}

Maanaim.Web/Views/Adm/Gerenciar.cshtml
@using Maanaim.Web.ExtensionMethods

@model List<Maanaim.Web.ViewModel.CalendarForm>;

<style>
    th, td {
        text-align: center
    }

    .label {
        color: dimgray
    }

    .label-success {
        background-color: rgb(230,230,230);
    }

    .label-warning {
        background-color: rgb(225,225,225);
    }
</style>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>
                <span>Programação</span>
                <br />
                Período (Início - Término)
            </th>
            <th>Ação</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var calendarItem in Model)
        {
            <tr>
                <td title="@calendarItem.Description.StripHTML()">
                    <span style="font-weight:bold">
                        <a href="Visualizar/@calendarItem.Id">@calendarItem.Title</a> <span class="label" style="background-color:@calendarItem.BackgroundColor; color:@calendarItem.TextColor">(@calendarItem.Ministry)</span>
                    </span>

                    <br />
                    <span class="btn btn-default">@calendarItem.StartDate</span>
                    <span class="btn btn-default">@calendarItem.EndDate</span>
                </td>
                <td>

                    @using (Html.BeginForm("Excluir", "Adm", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <input type="hidden" name="Id" value="@calendarItem.Id" />

                        @Html.ActionLink("Alterar", "IncluirAlterar", "Adm", new { Id = calendarItem.Id }, new { @class = "btn btn-primary" })

                        <button id="btnDelete" type="submit" class="btn btn-danger" onclick="return confirm('Confirma exclusão?')">Excluir</button>
                    }

                </td>
            </tr>
        }
    </tbody>

</table>

@{
    if (ViewBag.Message != null && ViewBag.MessageClass != null)
    {
        <div id="divMsg" class="alert @ViewBag.MessageClass">
            <strong>@ViewBag.Message</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
}

@section Scripts { 
        <script type="text/javascript">
            $(document).ready(function () {

                $("form").submit(function (event) {
                    $("#divModal").modal();
                });
            });


        </script>
}
    

Maanaim.Web/Views/Adm/IncluirAlterar.cshtml
@model Maanaim.Web.ViewModel.CalendarForm;

@section CSS {
    <environment include="Development">
        <link href="~/lib/Trumbowyg/ui/trumbowyg.css" rel="stylesheet" />
        <link href="~/lib/Trumbowyg/plugins/colors/ui/trumbowyg.colors.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link href="~/lib/Trumbowyg/ui/trumbowyg.min.css" rel="stylesheet" />
        <link href="~/lib/Trumbowyg/plugins/colors/ui/trumbowyg.colors.min.css" rel="stylesheet" />
    </environment>
    <style>
        .bootstrap-modal-selector {
            overflow-y: scroll;
        }
    </style>
}

@{
    if (ViewData["Message"] != null && ViewData["MessageClass"] != null)
    {
        <div id="divMsg" class="alert @ViewData["MessageClass"]">
            <strong>@ViewData["Message"]</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
}

@using (Html.BeginForm("IncluirAlterar", "Adm", FormMethod.Post))
{
    @Html.AntiForgeryToken()


    <div class="panel-heading">
        <div class="panel-title">
            <div style="font-weight: bold;">

                @if (string.IsNullOrEmpty(Model.Id))
                {
                    <h4>Incluir Programação no Calendário</h4>
                }
                else
                {
                    <h4>Alterar Programação no Calendário</h4>
                }
            </div>


        </div>


    </div>



    <div class="panel-body form-horizontal">

        <input type="hidden" name="Id" value="@Model.Id" />

        <div class="form-group">
            <label for="txtTitulo" class="col-sm-3 control-label inputDate">Título:</label>
            <div class="col-sm-6">
                <input type="text" ID="txtTitle" name="Title" class="form-control" value="@Model.Title" required />
            </div>
        </div>

        <div class="form-group">
            <label for="txtDescricao" class="col-sm-3 control-label inputDate">Descrição:</label>
            <div class="col-sm-6">

                <textarea ID="txtDescription" name="Description" class="form-control" required>@Model.Description</textarea>

            </div>
        </div>

        <div class="form-group">
            <label for="txtStart" class="col-sm-3 control-label inputDate">Início:</label>
            <div class="col-sm-6">
                <input type="text" ID="txtStart" name="StartDate" class="inputDateInicio form-control" placeholder="Data e Hora" value="@Model.StartDate" required />
            </div>
        </div>

        <div class="form-group">
            <label for="txtTermino" class="col-sm-3 control-label inputDate">Término:</label>
            <div class="col-sm-6">
                <input type="text" ID="txtEnd" name="EndDate" class="inputDateTermino form-control" placeholder="Data e Hora" value="@Model.EndDate" required />
            </div>
        </div>

        <div class="form-group">
            <label for="ddlMinisterio" class="col-sm-3 control-label">Ministério:</label>
            <div class="col-sm-6">
                <select id="ddlMinisterio" name="Ministry" class="form-control" required>
                    <option value="" backgroundcolor="#FFFFFF" textcolor="black">(Selecione um Ministério)</option>
                    <option value="ADMM" backgroundcolor="#fffacd" textcolor="#000000">Igreja em Geral</option>
                    <option value="ME" backgroundcolor="#617b4c" textcolor="#ffffff">Ministério de Ensino (Talmid)</option>
                    <option value="MJ" backgroundcolor="#9bc1e6" textcolor="#000000">Missão Jovem</option>
                    <option value="MM" backgroundcolor="#fcd966" textcolor="#000000">Ministério de Mulheres</option>
                    <option value="MH" backgroundcolor="#c9c9c9" textcolor="#000000">Ministério de Homens</option>
                    <option value="MF" backgroundcolor="#f3b085" textcolor="#000000">Ministério da Família</option>
                    <option value="MI" backgroundcolor="#315496" textcolor="#ffffff">Ministério de Intercessão</option>
                    <option value="SOMA" backgroundcolor="#fffe00" textcolor="#000000">Missão Soma</option>
                    <option value="MK" backgroundcolor="#ff3497" textcolor="#000000">Missão Kids</option>
                    <option value="MO" backgroundcolor="#fc5151" textcolor="#000000">Ministério de Obreiros</option>
                    <option value="MA" backgroundcolor="#fffacd" textcolor="#000000">Ministério Acolhida</option>
                    <option value="EF" backgroundcolor="#fffacd" textcolor="#000000">Estrutura Física</option>
                    <option value="ML" backgroundcolor="#548233" textcolor="#ffffff">Ministério de Louvor</option>
                    <option value="MEv" backgroundcolor="#7030a2" textcolor="#ffffff">Ministério de Eventos</option>
                    <option value="MS&Tec" backgroundcolor="#833d0c" textcolor="#ffffff">Mídias Sociais e Tecnologia</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <label for="colorBackground" class="col-sm-3 control-label">Cor de Fundo:</label>
            <div class="col-sm-6">
                <input type="color" ID="colorBackground" name="BackgroundColor" class="form-control" value="#fffacd" />
            </div>
        </div>

        <div class="form-group">
            <label for="colorText" class="col-sm-3 control-label">Cor do Texto:</label>
            <div class="col-sm-6">
                <input type="color" ID="colorText" name="TextColor" class="form-control" value="#fffff" />
            </div>
        </div>

        <div class="form-group">
            <label for="colorText" class="col-sm-3 control-label">Pré-visualização da combinação de cores:</label>
            <div class="col-sm-6">
                <input type="text" ID="txtColorPreview" class="form-control" value="[Título a ser apresentado]" style="background-color:#fffacd; color:#000000" readonly="readonly" />
            </div>
        </div>




    </div>


    <div class="panel-footer text-right">

        <button id="btnSave" type="submit" class="btn btn-success">Salvar</button>

        <a class="btn btn-danger" href="/" role="button">Cancelar</a>

    </div>

}



<div class="row">
    <div class="col-sm-12">
        <asp:Literal ID="ltlInclusaoMsg" runat="server"></asp:Literal>
    </div>
</div>

@section Scripts {

    <environment include="Development">
        <script src="~/lib/fullcalendar/fullcalendar.js"></script>
        <script src="~/lib/fullcalendar/locale/pt-br.js"></script>
        <script src="~/lib/Trumbowyg/trumbowyg.js"></script>
        <script src="~/lib/Trumbowyg/plugins/colors/trumbowyg.colors.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/fullcalendar/fullcalendar.min.js"></script>
        <script src="~/lib/fullcalendar/locale/pt-br.min.js"></script>
        <script src="~/lib/Trumbowyg/trumbowyg.min.js"></script>
        <script src="~/lib/Trumbowyg/plugins/colors/trumbowyg.colors.min.js"></script>
    </environment>

    <script type="text/javascript">
        $(document).ready(function () {

            var dateNow = new Date();

            $(".inputDateInicio").datetimepicker({ locale: "pt-BR", format: "DD/MM/YYYY HH:mm:ss", defaultDate: dateNow, sideBySide: true });

            $(".inputDateTermino").datetimepicker({ locale: "pt-BR", format: "DD/MM/YYYY HH:mm:ss", defaultDate: dateNow, sideBySide: true });

            $("#colorBackground,#colorText").change(
                function () {
                    var bgColor = $("#colorBackground").val();
                    var txtColor = $("#colorText").val();
                    $("#txtColorPreview").css("background-color", bgColor);
                    $("#txtColorPreview").css("color", txtColor);
                }
            );

            $("#ddlMinisterio").change(
                function () {

                    var backgroundcolor = $(this).find("option:selected").attr("backgroundcolor");
                    $("#colorBackground").val(backgroundcolor);

                    var textcolor = $(this).find("option:selected").attr("textcolor");
                    $("#colorText").val(textcolor);

                    $("#colorBackground").trigger("change");
                }
            );

            $('#txtDescription').trumbowyg(
                {
                    btns: ['foreColor', 'backColor',
                        ['viewHTML'],
                        ['undo', 'redo'], // Only supported in Blink browsers
                        ['formatting'],
                        ['strong', 'em', 'del'],
                        ['superscript', 'subscript'],
                        ['link'],
                        ['insertImage'],
                        ['justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
                        ['unorderedList', 'orderedList'],
                        ['horizontalRule'],
                        ['removeformat'],
                        ['fullscreen']
                    ]
                }
            );

            $("#txtTitle").change(
                function () {
                    var txt = $("#txtTitle").val();
                    if (txt == "")
                        txt = "[Título a ser apresentado]";
                    $("#txtColorPreview").val(txt);
                }
            );

            $("form").submit(function (event) {
                $("#divModal").modal();
            });



            setTimeout(
                function () {
                    $(".alert-success").fadeOut();
                }, 4000
            );




            @if (!string.IsNullOrEmpty(Model.Ministry))
            {
                <text>
            $('#ddlMinisterio').val('@Html.Raw(Model.Ministry)');
            $("#ddlMinisterio").trigger("change");
                </text>
            }



        });


    </script>

}

Maanaim.Web/Views/Adm/Index.cshtml
@using Maanaim.Web.ExtensionMethods

@model List<Maanaim.Model.Calendar>;

@section CSS {
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/fullcalendar/fullcalendar.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/fullcalendar/fullcalendar.min.css" />
    </environment>
}


<div id="calendar">
</div>

@section Scripts {

    <environment include="Development">
        <script src="~/lib/fullcalendar/fullcalendar.js"></script>
        <script src="~/lib/fullcalendar/locale/pt-br.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/fullcalendar/fullcalendar.min.js"></script>
        <script src="~/lib/fullcalendar/locale/pt-br.js"></script>
    </environment>

    <script>

        var eventsList = [
            @{ 
                bool first = true;
                foreach(var calendarItem in Model)
                {
                    if (!first)
                    {
                        <text>,</text>
                    }
                    <text>
            {
                title: '@Html.Raw(calendarItem.Title)',
                start: '@calendarItem.StartDate.ToFullCalendar()',
                end: '@calendarItem.EndDate.ToFullCalendar()',
                color: '@calendarItem.BackgroundColor',
                textColor: '@calendarItem.TextColor',
                url: '@this.ViewContext.RouteData.Values["controller"].ToString()/Visualizar/@calendarItem.Id'
            }
                    </text>
                    first = false;
                }
            }
        ];

        $(document).ready(function () {

            $('#calendar').fullCalendar({
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'month,agendaWeek,agendaDay,listWeek'
                },
                defaultDate: '@System.DateTime.Now.ToString("yyyy-MM-dd")',
                navLinks: true, // can click day/week names to navigate views
                editable: true,
                eventLimit: true, // allow "more" link when too many events
                events: eventsList
            });

        });

    </script>
}

Maanaim.Web/Views/Adm/Visualizar.cshtml
@model Maanaim.Web.ViewModel.CalendarForm;

@section CSS {
    
}

@using (Html.BeginForm("IncluirAlterar", "Home", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="panel-heading">
        <div class="panel-title">
            <div style="font-weight: bold;">

                <h3>@Model.Title</h3>
            </div>


        </div>


    </div>



    <div class="panel-body form-horizontal">

        <div class="form-group">
            <div class="col-sm-12">
                @Html.Raw(@Model.Description)
            </div>
        </div>

        <br />
        
        <div class="form-group">
            <label for="txtStart" class="col-sm-3 control-label inputDate">Início:</label>
            <div class="col-sm-6">
                <input type="text" ID="txtStart" name="StartDate" class="inputDateInicio form-control" placeholder="Data e Hora" value="@Model.StartDate" readonly="readonly" />
            </div>
        </div>

        <div class="form-group">
            <label for="txtTermino" class="col-sm-3 control-label inputDate">Término:</label>
            <div class="col-sm-6">
                <input type="text" ID="txtEnd" name="EndDate" class="inputDateTermino form-control" placeholder="Data e Hora" value="@Model.EndDate" readonly="readonly" />
            </div>
        </div>

        <div class="form-group">
            <label for="ddlMinisterio" class="col-sm-3 control-label">Ministério:</label>
            <div class="col-sm-6">
                <select id="ddlMinisterio" name="Ministry" class="form-control" disabled="disabled" required>
                    <option value="">(Selecione um Ministério)</option>
                    <option value="ADMM">Igreja em Geral</option>
                    <option value="ME">Ministério de Ensino (Talmid)</option>
                    <option value="MJ">Missão Jovem</option>
                    <option value="MM">Ministério de Mulheres</option>
                    <option value="MH">Ministério de Homens</option>
                    <option value="MF">Ministério da Família</option>
                    <option value="MI">Ministério de Intercessão</option>
                    <option value="SOMA">Missão Soma</option>
                    <option value="MK">Missão Kids</option>
                    <option value="MO">Ministério de Obreiros</option>
                    <option value="MA">Ministério Acolhida</option>
                    <option value="EF">Estrutura Física</option>
                    <option value="ML">Ministério de Louvor</option>
                    <option value="MEv">Ministério de Eventos</option>
                    <option value="MS&Tec">Mídias Sociais e Tecnologia</option>
                </select>
            </div>
        </div>




    </div>


    <div class="panel-footer text-center">

        <a class="btn btn-info" href="javascript:history.back();" role="button">Voltar</a>

    </div>

}



<div class="row">
    <div class="col-sm-12">
        <asp:Literal ID="ltlInclusaoMsg" runat="server"></asp:Literal>
    </div>
</div>

@section Scripts {

    <script type="text/javascript">
        $(document).ready(function () {
            
            @if (!string.IsNullOrEmpty(Model.Ministry))
            {
                <text>
                $('#ddlMinisterio').val('@Html.Raw(Model.Ministry)');
                </text>
            }



        });


    </script>

}

Maanaim.Web/Views/Home/Gerenciar.cshtml
@using Maanaim.Web.ExtensionMethods

@model List<Maanaim.Web.ViewModel.CalendarForm>;

<style>
    th, td {
        text-align: center
    }

    .label {
        color: dimgray
    }

    .label-success {
        background-color: rgb(230,230,230);
    }

    .label-warning {
        background-color: rgb(225,225,225);
    }
</style>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>
                <span>Programação</span>
                <br />
                Período (Início - Término)
            </th>
            <th>Ação</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var calendarItem in Model)
        {
            <tr>
                <td title="@calendarItem.Description.StripHTML()">
                    <span style="font-weight:bold">
                        <a href="Visualizar/@calendarItem.Id">@calendarItem.Title</a> <span class="label" style="background-color:@calendarItem.BackgroundColor; color:@calendarItem.TextColor">(@calendarItem.Ministry)</span>
                    </span>

                    <br />
                    <span class="btn btn-default">@calendarItem.StartDate</span>
                    <span class="btn btn-default">@calendarItem.EndDate</span>
                </td>
                <td>

                    @using (Html.BeginForm("Excluir", "Home", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <input type="hidden" name="Id" value="@calendarItem.Id" />

                        @Html.ActionLink("Alterar", "IncluirAlterar", "Home", new { Id = calendarItem.Id }, new { @class = "btn btn-primary" })

                        <button id="btnDelete" type="submit" class="btn btn-danger" onclick="return confirm('Confirma exclusão?')">Excluir</button>
                    }

                </td>
            </tr>
        }
    </tbody>

</table>

@{
    if (ViewBag.Message != null && ViewBag.MessageClass != null)
    {
        <div id="divMsg" class="alert @ViewBag.MessageClass">
            <strong>@ViewBag.Message</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
}

@section Scripts { 
        <script type="text/javascript">
            $(document).ready(function () {

                $("form").submit(function (event) {
                    $("#divModal").modal();
                });
            });


        </script>
}
    

Maanaim.Web/Views/Home/Index.cshtml
@using Maanaim.Web.ExtensionMethods

@model List<Maanaim.Model.Calendar>;

@section CSS {
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/fullcalendar/fullcalendar.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/fullcalendar/fullcalendar.min.css" />
    </environment>
}


<div id="calendar">
</div>

@section Scripts {

    <environment include="Development">
        <script src="~/lib/fullcalendar/fullcalendar.js"></script>
        <script src="~/lib/fullcalendar/locale/pt-br.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/fullcalendar/fullcalendar.min.js"></script>
        <script src="~/lib/fullcalendar/locale/pt-br.min.js"></script>
    </environment>

    <script>

        var eventsList = [
            @{ 
                bool first = true;
                foreach(var calendarItem in Model)
                {
                    if (!first)
                    {
                        <text>,</text>
                    }
                    <text>
            {
                title: '@calendarItem.Title',
                start: '@calendarItem.StartDate.ToFullCalendar()',
                end: '@calendarItem.EndDate.ToFullCalendar()',
                color: '@calendarItem.BackgroundColor',
                textColor: '@calendarItem.TextColor',
                url: 'Home/Visualizar/@calendarItem.Id?@(Context.Request.Query["readonly"]=="1"?"readonly=1":"")'
            }
                    </text>
                    first = false;
                }
            }
        ];

        $(document).ready(function () {

            $('#calendar').fullCalendar({
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'month,agendaWeek,agendaDay,listWeek'
                },
                defaultDate: '@System.DateTime.Now.ToString("yyyy-MM-dd")',
                navLinks: true, // can click day/week names to navigate views
                editable: true,
                eventLimit: true, // allow "more" link when too many events
                events: eventsList
            });

        });

    </script>
}